version: '3.7'
services:
  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  server:
    build: server
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
    volumes:
      - $HOME/.m2:/root/.m2
  redis:
    image: redis:5.0.0-alpine
  client:
    build: client
    depends_on:
      - server
  nginx:
    image: nginx:1.15.5-alpine
    ports:
      - 3000:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
      - client
